##
## just for quick testing
##

on:
  push:
    branches:
      fork-buildargs
  workflow_dispatch:

jobs:
  make_build_tag:
    runs-on: ubuntu-22.04
    steps:
      - name: Creating Build Number Tag
        run: |
          echo "mary was here"


