##
## just for quick testing
##

on:
  push:
    branches:
      fork-buildargs
  workflow_dispatch:

jobs:
  make_build_tag:
    runs-on: ubuntu-22.04
    steps:
      - name: Get short commit hash
        run: echo "GIT_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Get tag
        run: echo "GIT_LATEST_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
      - name: Creating Build Number Tag
        run: |
          echo "mary was here"
          echo "git commit: ${{ env.GIT_COMMIT }}"
          echo "git latest tag: ${{ env.GIT_LATEST_TAG}}"

